#!/bin/bash

# Based from Mental Outlaws aliasrc

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias \
	myip="curl ipinfo.io/ip" \
	untar="tar -zxvf" \
	sha="shasum -a 256" \
	cp="cp -iv" \
	cl="clear" \
	rm="rm -v" \
	mv="mv -iv" \
	mkdir="mkdir -pv" \
	g="git" \
	ga="git add" \
	gc="git commit" \
	gp="git push" \
	gs="git status" \
	gcl="git clone" \
	gd="git diff" \
	pmadd="sudo pacman -S" \
	pmare="sudo pacman -R" \
	vialias="nvim ~/.config/.aliasrc" \
	vizshrc="nvim ~/.zshrc" \
	ls="ls --color=tty" \
